import {_electron as electron} from "playwright";
import assert from "node:assert/strict";
import {mkdirSync,writeFileSync} from "node:fs";
import path from "node:path";
const root=path.resolve(import.meta.dirname,"../.."),folder=path.join(root,"artifacts/m1");
mkdirSync(folder,{recursive:true});
const executablePath=path.join(root,"desktop/out/RevitThyme-win32-x64/RevitThyme.exe");
const app=await electron.launch({executablePath,timeout:15000});
const checks=[],errors=[];
function check(value,name){assert.ok(value,name);checks.push({name,passed:true});console.log("PASS: "+name);}
let page;
try{
 page=await app.firstWindow();page.setDefaultTimeout(15000);page.on("pageerror",e=>errors.push(String(e)));
 await page.getByRole("button",{name:"Review Apply",exact:true}).waitFor({timeout:15000});
 await page.waitForFunction(()=>!document.querySelector('[aria-label="Review Apply"]')?.getAttribute("aria-disabled"));
 check((await page.getByLabel("Cut Plane offset").inputValue()).startsWith("1219.2"),"Packaged Expo loads assets and Rust preview through preload");
 check(await page.evaluate(()=>{try{window.require("node:fs");return false;}catch{return !window.process?.versions?.node;}}),"Renderer cannot access Node filesystem or native process");
 check(await page.evaluate(()=>Object.keys(window.revitthyme).sort().join(",")==="capture,preview,propose,reconnect"),"Narrow named bridge has no credential/file/shell/URL method");
 await page.getByLabel("Cut Plane offset").fill("1524");
 await page.waitForFunction(()=>document.querySelector('[aria-label="Cut Plane offset"]')?.value==="1524");
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 await page.getByText("Apply preview · proposed change",{exact:true}).waitFor();
 check((await page.getByText(/Cut Plane · Level 1/).textContent()).includes("→ 5 ft"),"Numeric offset passes Rust conversion and before/after proposal");
 check(await page.getByRole("button",{name:"Native Apply unavailable"}).isDisabled(),"Offline preview cannot write Revit");
 await page.getByRole("button",{name:"Reset",exact:true}).click();
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 await page.getByText("Apply preview · identical values",{exact:true}).waitFor();
 check(true,"Reset preserves captured exact values");
 await page.getByLabel("Display units").selectOption("ft");
 await page.waitForFunction(()=>document.querySelector('[aria-label="Cut Plane offset"]')?.value.startsWith("4.000"));
 await page.getByLabel("Cut Plane offset").fill("NaN");
 check(await page.getByRole("button",{name:"Review Apply",exact:true}).isDisabled(),"Nonfinite input disables review");
 await page.getByLabel("Cut Plane offset").fill("5");
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 await page.getByText("Apply preview · proposed change",{exact:true}).waitFor();
 await page.keyboard.press("Escape");
 await page.getByText("Cancelled. Captured values restored; no model changes.",{exact:true}).waitFor();
 check(true,"Escape cancels without mutation");
 await page.getByLabel("Top offset").fill("bad");
 await page.getByLabel("Bottom offset").fill("bad");
 await page.getByLabel("Bottom offset").fill("0");
 check(await page.getByRole("button",{name:"Review Apply",exact:true}).isDisabled(),"One valid row cannot clear another invalid row");
 await page.getByRole("button",{name:"Reset",exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[aria-label="Top offset"]')?.value==="8");
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 await page.getByText("Apply preview · identical values",{exact:true}).waitFor();
 check(true,"Reset restores invalid text buffers and exact values");
 await page.getByLabel("Cut Plane offset").fill("20");
 await page.getByText(/Top must be above Cut/).waitFor();
 check(await page.getByRole("button",{name:"Review Apply",exact:true}).isDisabled(),"Native rule precheck rejects invalid plane order");
 await page.getByRole("button",{name:"Reset",exact:true}).click();
 await app.evaluate(()=>{
   const original=globalThis.fetch;
   globalThis.fetch=async(input,init)=>{
     const response=await original(input,init);
     if(String(input).endsWith("/v1/preview") && JSON.parse(init.body).edits.cut.value===5)
       await new Promise(resolve=>setTimeout(resolve,600));
     return response;
   };
 });
 await page.getByLabel("Cut Plane offset").fill("5");
 await page.waitForTimeout(100);
 await page.getByLabel("Cut Plane offset").fill("6");
 await page.waitForTimeout(800);
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 await page.getByText("Apply preview · proposed change",{exact:true}).waitFor();
 check((await page.getByText(/Cut Plane · Level 1/).textContent()).includes("→ 6 ft") && await page.getByLabel("Cut Plane offset").inputValue()==="6","Delayed old response cannot overwrite newer input");
 const cutSlider=page.getByLabel("Cut Plane slider");
 await cutSlider.focus();await page.keyboard.press("ArrowLeft");
 await page.waitForTimeout(100);
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 check(!(await page.getByText(/Cut Plane · Level 1/).textContent()).includes("→ 6 ft"),"Keyboard operates plane slider");
 const line=page.getByLabel("Cut Plane plane drag");const box=await line.boundingBox();
 await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y+box.height/2-20,{steps:4});await page.mouse.up();
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 check(true,"Pointer drags section plane through typed preview");
 await page.getByLabel("Slice axis").selectOption("x");
 await page.getByLabel("Slice position").fill("0.4");
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 check(true,"Slice locator and axis recompute the Rust section");
 await page.getByLabel("Top Unlimited").check();
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 check((await page.getByText(/Top · Level 1/).textContent()).includes("→ Unlimited"),"Unlimited is preserved and reviewed");
 await page.getByRole("button",{name:"Reset",exact:true}).click();
 for(const kind of ["ceiling","engineering"]){
   await page.getByLabel("Fixture view").selectOption(kind);
   await page.getByRole("button",{name:"Refresh fixture",exact:true}).click();
   await page.getByRole("button",{name:"Review Apply",exact:true}).click();
   await page.getByText("Apply preview · identical values",{exact:true}).waitFor();
   check(true,"Supported fixture range: "+kind);
 }
 await page.getByLabel("Partial capture fixture").check();
 await page.getByRole("button",{name:"Refresh fixture",exact:true}).click();
 await page.getByText("Partial fixture: triangle limit deliberately omits slabs and furniture.",{exact:true}).waitFor();
 check(await page.getByText("Apply preview · identical values",{exact:true}).count()===0,"Partial capture is visible and refresh clears old confirmation");
 await page.getByLabel("Partial capture fixture").uncheck();
 await page.getByLabel("Fixture view").selectOption("floor");
 await page.getByRole("button",{name:"Refresh fixture",exact:true}).click();
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 const before=await page.evaluate(()=>window.revitthyme.capture({protocol:1,view_kind:"floor",partial_fixture:false}));
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 await page.getByText(/stale_snapshot/).waitFor();
 check(true,"Out of date displayed target is rejected");
 await page.getByRole("button",{name:"Reconnect",exact:true}).click();
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 const after=await page.evaluate(()=>window.revitthyme.capture({protocol:1,view_kind:"floor",partial_fixture:false}));
 check(before.target.session_id!==after.target.session_id,"Reconnect starts a fresh owned sidecar session");
 await page.getByRole("button",{name:"Refresh fixture",exact:true}).click();
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 const forged=await app.evaluate(async({app,BrowserWindow})=>{
   const foreign=new BrowserWindow({show:false,webPreferences:{preload:app.getAppPath()+"/build/preload.cjs",sandbox:true,contextIsolation:true,nodeIntegration:false}});
   await foreign.loadURL("about:blank");
   const result=await foreign.webContents.executeJavaScript('window.revitthyme.capture({protocol:1,view_kind:"floor",partial_fixture:false}).then(()=>"accepted",e=>e.message)');
   foreign.destroy();return result;
 });
 check(forged.includes("Untrusted IPC sender"),"Packaged IPC rejects an unrelated window");
 check(await page.evaluate(async()=>{try{await fetch("http://127.0.0.1:9/");return false;}catch{return true;}}),"CSP rejects arbitrary renderer network access");
 await page.getByRole("button",{name:"Dark theme"}).click();
 check(await page.evaluate(()=>document.documentElement.classList.contains("dark")),"Dark theme is readable through packaged CSS");
 await page.screenshot({path:path.join(folder,"packaged-dark.png"),fullPage:true});
 await page.getByRole("button",{name:"Light theme"}).click();
 await page.screenshot({path:path.join(folder,"packaged-light.png"),fullPage:true});
 await page.getByRole("link",{name:"About this preview",exact:true}).click();
 await page.getByRole("link",{name:"Back to Visual View Range"}).waitFor();
 check(new URL(page.url()).protocol==="app:","Packaged Expo navigation uses local application protocol");
 await page.getByRole("link",{name:"Back to Visual View Range"}).click();
 await page.getByRole("button",{name:"Review Apply",exact:true}).click();
 const url=page.url();
 await page.evaluate(()=>{window.location.href="https://example.invalid/";});
 await page.waitForTimeout(100);
 check(page.url()===url,"Untrusted navigation is blocked");
 check(errors.length===0,"No renderer errors");
 console.log(checks.length+" packaged UI observations pass.");
} catch(e){if(page)await page.screenshot({path:path.join(folder,"ui-failure.png"),fullPage:true}).catch(()=>{});console.error("Renderer errors:",errors);throw e;}
finally {await app.close();writeFileSync(path.join(folder,"ui-evidence.json"),JSON.stringify({scope:"packaged_application",executablePath,checks,errors,actual_revit:false},null,2)+"\n");}
